version: '3.9'

networks: 
  quiz:
    driver: bridge

volumes: 
  dbData: 
    driver: local

services: 
  app:
    build: .
    ports:
      - 3000:3000
      - 8081:8081
    volumes:
      - .:/app
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - quiz

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - dbData:/var/lib/mysql
    environment:
      MYSQL_DATABASE: quiz
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - quiz
